# Generated by Django 5.0.7 on 2024-08-06 10:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("management", "0002_doctorinfo"),
    ]

    operations = [
        migrations.CreateModel(
            name="Patientdetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("pat_name", models.CharField(max_length=50)),
                ("age", models.CharField(max_length=50)),
                ("date", models.CharField(max_length=50)),
                ("problem", models.CharField(max_length=50)),
            ],
        ),
    ]
