# Generated by Django 5.0.7 on 2024-08-06 10:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("management", "0003_patientdetails"),
    ]

    operations = [
        migrations.RenameField(
            model_name="patientdetails",
            old_name="name",
            new_name="dc_name",
        ),
    ]
