# Generated by Django 5.0.7 on 2024-08-06 11:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("management", "0005_rename_pat_name_patientdetails_patname"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patientdetails",
            name="age",
            field=models.IntegerField(max_length=50),
        ),
        migrations.AlterField(
            model_name="patientdetails",
            name="date",
            field=models.IntegerField(max_length=50),
        ),
    ]
