# Generated by Django 5.0.7 on 2024-08-06 11:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("management", "0006_alter_patientdetails_age_alter_patientdetails_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patientdetails",
            name="age",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="patientdetails",
            name="date",
            field=models.IntegerField(),
        ),
    ]
