# Generated by Django 5.0.7 on 2024-08-07 10:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("management", "0007_alter_patientdetails_age_alter_patientdetails_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="doctorlogin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=50)),
                ("identity", models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name="patientdetails",
            name="date",
            field=models.DateField(),
        ),
    ]
